services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Vinh123456789."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    networks:
      lab1-api-networks:

  lab1-api:
    container_name: lab1_api
    image: lab1-aspnet:latest
    networks:
      lab1-api-networks:
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
    restart: always

networks:
  lab1-api-networks:
    name: lab1_api_networks

volumes:
  sql_data: